import Link from "next/link";

import { AppShell } from "@/components/shell/app-shell";
import { SectionCard } from "@/components/shell/section-card";
import { peekInvite } from "@/server/auth/flows";

type InvitePageProps = {
  searchParams: Promise<{
    token?: string;
    error?: string;
  }>;
};

export default async function InvitePage({ searchParams }: InvitePageProps) {
  const { token, error } = await searchParams;
  const inviteTarget = token ? await peekInvite(token) : null;
  const errorMessage =
    error === "missing-fields"
      ? "Complete all fields before accepting the invitation."
      : error === "password-mismatch"
        ? "The password confirmation did not match."
        : error === "invalid-token"
          ? "This invitation link is invalid or expired. Ask an admin to send a new one."
          : error === "unavailable"
            ? "The invitation could not be completed right now."
            : null;

  return (
    <AppShell
      eyebrow="Authentication v2"
      title="Accept invitation"
      description="Set the first password for your Fleet Crisis Ops member account and continue into email verification."
      actions={
        <div className="flex flex-wrap gap-3">
          <Link
            href="/"
            className="action-button-light rounded-full border border-foreground bg-foreground px-4 py-2 text-sm font-semibold shadow-sm shadow-slate-900/10"
          >
            Open access portal
          </Link>
        </div>
      }
    >
      <SectionCard
        title="Account setup"
        description="Invitations are generated by a super admin after the role and captain ship assignment are already decided."
      >
        <div className="grid gap-4">
          {errorMessage ? (
            <p className="rounded-2xl border border-accent-strong/20 bg-orange-50/80 px-4 py-3 text-sm text-accent-strong">
              {errorMessage}
            </p>
          ) : null}

          {!token || !inviteTarget ? (
            <div className="rounded-2xl border border-line bg-white/70 p-4 text-sm leading-7 text-muted">
              This invitation is missing, expired, or has already been used.
            </div>
          ) : (
            <form action="/api/auth/invite/accept" method="post" className="grid gap-3">
              <input type="hidden" name="token" value={token} />
              <div className="rounded-2xl border border-line bg-white/70 p-4 text-sm leading-7 text-muted">
                Invitation for{" "}
                <span className="font-semibold text-foreground">{inviteTarget.email}</span>
              </div>
              <label className="grid gap-2 text-sm text-foreground">
                <span className="font-semibold uppercase tracking-[0.16em] text-muted">
                  Full name
                </span>
                <input
                  name="fullName"
                  defaultValue={inviteTarget.fullName ?? ""}
                  className="rounded-2xl border border-line bg-white/90 px-4 py-3 text-sm text-foreground"
                />
              </label>
              <label className="grid gap-2 text-sm text-foreground">
                <span className="font-semibold uppercase tracking-[0.16em] text-muted">
                  Password
                </span>
                <input
                  name="password"
                  type="password"
                  className="rounded-2xl border border-line bg-white/90 px-4 py-3 text-sm text-foreground"
                />
              </label>
              <label className="grid gap-2 text-sm text-foreground">
                <span className="font-semibold uppercase tracking-[0.16em] text-muted">
                  Confirm password
                </span>
                <input
                  name="confirmPassword"
                  type="password"
                  className="rounded-2xl border border-line bg-white/90 px-4 py-3 text-sm text-foreground"
                />
              </label>
              <button
                type="submit"
                className="action-button-light rounded-full border border-accent bg-accent px-4 py-3 text-sm font-semibold shadow-sm shadow-accent/20"
              >
                Accept invitation
              </button>
            </form>
          )}
        </div>
      </SectionCard>
    </AppShell>
  );
}
